### ISSUE TITLE
Requesting Attachments of documents 

### ISSUE THREAD

**Issue by dilipmech1993** [Dilip-Mech/WhatsUp_Development#3]
Dear Dilip,

It would be great if the app is capable of attaching the documents as well.

Kindly add this feature.

**Comment by Dilip-Mech** [comment]
Dear user thanks for your suggestion for this feature we will add and let you know.

**Comment by Dilip-Mech** [comment]
Dear user, 
   Thanks for your valuable suggestion. This feature is going to make our product great.
